### ISSUE TITLE
BRUSHUP : Orientation guidance arrows (yellow arrows) not displayed when device is rotated

### ISSUE THREAD

**Issue by tawfik-azzabi** [GamesThatWork/BrushUpBuilds#168]
Environment
- App: BrushDown
- Build: v1.5.142
- Platforms: iOS/Windows/Android

Description
The yellow orientation guidance arrows, which are expected to appear when the user rotates the device away from the required landscape orientation, do not appear.
These arrows are supposed to prompt the user to rotate the phone back to landscape mode to ensure correct video capture and display.

Steps to Reproduce
- Launch the app
- Start a game or video recording flow.
- Rotate the device from landscape to portrait (normal vertical).
- Rotate the device further to portrait upside-down (head down).

Expected Result
- When the device is not in landscape orientation, yellow arrows should appear clearly on screen.
- The arrows should consistently prompt the user to rotate the phone back to landscape.

**Comment by tawfik-azzabi** [comment]
This is only a suggestion outside my role of a tester : 
As an alternative to orientation prompts, have you considered the possibility of locking the screen orientation to landscape during gameplay, as commonly done in many mobile games ?
This could prevent invalid orientations altogether and reduce user error.

**Comment by DovJacobson** [comment]
Ii appreciate your suggestion, Tawfik
I call   "screen.orientation.lock('landscape-primary')"
it is ignored in many situations (especially by ios)
but maybe I can be more insistent...

**Comment by DovJacobson** [comment]
1.5.143 corrects a race condition that might have been blocking the
orienatation lock call
should be fine in android  (do we have android problems?)
but might not fix ios

**Comment by tawfik-azzabi** [comment]
@DovJacobson On all platforms iOS, Android and windows at app launch the application remains stuck on the home screen.
The central video area is completely black, and the app version is not displayed (see screenshot below) 

<img width="2880" height="1920" alt="Image" src="https://github.com/user-attachments/assets/51082008-7a8e-48a3-9815-a06a91bc66f0" />

**Comment by DovJacobson** [comment]
thanks -- will find error

**Comment by DovJacobson** [comment]
fixed in 1.5.147 and sorry for long delay

**Comment by tawfik-azzabi** [comment]
Yes, it's fixed Actually in v1.5.146 thank you !

Here's an update about the display orientation:

Android : 
- Issue resolved. The screen is now correctly locked in landscape mode, even when rotating the device to portrait. 
- Notice : the game feels more stable and consistent from a user perspective.

iOS/Windows : 
- Issue still reproductible in v1.5.146. The screen orientation isn't locked to ladnscape orientation and the yellow arrows are not displayed when the device is rotated

**Comment by DovJacobson** [comment]
thanks for this testing.
happy about your android observation.
frustrated by the ios (ios26??) results. and will investigate further>

confused by the windows report, because windows devices are generally laptop/desktop and do not support any other orientation than landscape.   or am i missing something?

**Comment by tawfik-azzabi** [comment]
Yes, on iPhone I am testing on iOS 26.

Regarding Windows: I am using a Surface Pro, which behaves like a tablet. It supports device rotation, and while it is by default in landscape, the orientation is not locked. When the device is rotated, the app does not enforce landscape like it now does on Android.

So the observation is specific to tablet-like Windows devices (Surface Pro), not standard laptops/desktops.

**Comment by DovJacobson** [comment]
thanks for the clarification -- i w3ill investigate
meanwhile specific ios26 fixes were just implemented in 1.5.147 (number is
correct this time)
hopefully deployed by the time you read this

**Comment by tawfik-azzabi** [comment]
I just tested v1.5.147 on iPhone15 / iOS26.

Current behavior:
- When the phone is held in portrait, the app switches to landscape but we can't see all the homepage - screenshot1 below
- When the phone is physically rotated to landscape, the home screen flips/inverts and the layout breaks (UI decomposes) - screenshot2 below
So the orientation lock is partially working, but the layout becomes unstable when the device is actually rotated.

PORTRAIT MODE :
<img width="295" height="628" alt="Image" src="https://github.com/user-attachments/assets/a6e0a882-9541-4045-a7ec-004a559bdcad" />

LANDSCAPE MODE : iphone is physically rotated to landscape mode 
<img width="1378" height="645" alt="Image" src="https://github.com/user-attachments/assets/90b45f86-dad2-43aa-814a-b133ac1a2428" />

**Comment by DovJacobson** [comment]
wow -- thanks... oh boy

can you please play through a little on ios26 and let me know how the
camera behaves when in landscape mode.
how does it look in the "mirror"?
how does it present in the match game?
be aware of left/right flip - among other things. it is supposed to be
flipped like a real mirror.

**Comment by tawfik-azzabi** [comment]
Sorry Dov, I missed your last message.

At the moment on iOS26, I’m blocked at the home screen: the app does not allow me to proceed further, so I can’t start the video or reach the camera flow yet.

As soon as the home screen issue is cleared and I can start recording camera behaviour

**Comment by DovJacobson** [comment]
okay thanks  -- i was wqaitinfg for your report befoe addressing this
but i guess i had better fx it first!!

are you saying that the game is unresponsive?
does the animation happen?

**Comment by tawfik-azzabi** [comment]
The game is not responsive at all, the homepage is stuck as you can see above, there's no way to go further in the game 

![image](https://github.com/user-attachments/assets/cc4a58eb-9030-41f8-ab2c-31bf6bbe478f)

**Comment by DovJacobson** [comment]
@tawfik-azzabi    Please check ios26 performance on builds 1.5.151+  Thanks

**Comment by tawfik-azzabi** [comment]
@DovJacobson Quick update after testing build v1.5.151 on iOS26:

- Home screen: no longer blocked, I can now enter the game.
- Orientation behavior: the game is not locked to landscape. When the device is held in portrait, the yellow arrows correctly prompt the user to rotate to landscape. However, the transition from portrait to landscape is not smooth, the video appears slightly choppy during the rotation.
- End of game / Store: the background appears inverted on the store screen after finishing a game. This looks identical to a previous issue that was recently closed.

Let me know if you want me to reopen that last issue or log it as a regression.

**Comment by DovJacobson** [comment]
**no longer blocked**
Good

 **not locked to landscape**
Good

 **yellow arrows correct**
Good

 **video appears slightly choppy during the rotation**
Bad, of course. Most of these "good" results come from a new process for measuring aspect ratio that enforces a 'settling' delay to prevent a 'race condition' bug might account for most of the earlier problems. But this delay is certain to make the orientation response feel a little choppy. I used a 500msec delay to see if the race condition is the real culprit. 
This seems to be the case!!
Now I have reduced the delay to 250msec to see if it feels better to the user while still thwarting the race condition. Please try it using your Barby iPhone or even your older slower one if your daughter is sleeping 😉
(JK)


 **Background appears inverted...reopen. or log it as a regression?**
reopen, please.  grrr. if sure it is the same thing not similar

**Comment by DovJacobson** [comment]
@tawfik-azzabi Please close 168 if the issue is resolved
